package reddit

const sampleOutput = `
{
  "kind": "Listing",
  "data": {
    "after": null,
    "dist": 4,
    "facets": {},
    "modhash": "5smoo3xako8ff7ea37bc66f50d6a017f1bed5eca6964b98353",
    "children": [
      {
        "kind": "t3",
        "data": {
          "approved_at_utc": null,
          "subreddit": "linux",
          "selftext": "",
          "author_fullname": "t2_4x6jq",
          "saved": false,
          "mod_reason_title": null,
          "gilded": 0,
          "clicked": false,
          "title": "Why aren’t we using SSH for everything?",
          "link_flair_richtext": [],
          "subreddit_name_prefixed": "r/linux",
          "hidden": false,
          "pwls": 6,
          "link_flair_css_class": null,
          "downs": 0,
          "thumbnail_height": 54,
          "top_awarded_type": null,
          "hide_score": false,
          "name": "t3_2r539r",
          "quarantine": false,
          "link_flair_text_color": "dark",
          "upvote_ratio": 0.95,
          "author_flair_background_color": null,
          "subreddit_type": "public",
          "ups": 880,
          "total_awards_received": 0,
          "media_embed": {},
          "thumbnail_width": 140,
          "author_flair_template_id": null,
          "is_original_content": false,
          "user_reports": [],
          "secure_media": null,
          "is_reddit_media_domain": false,
          "is_meta": false,
          "category": null,
          "secure_media_embed": {},
          "link_flair_text": null,
          "can_mod_post": false,
          "score": 880,
          "approved_by": null,
          "author_premium": true,
          "thumbnail": "https://b.thumbs.redditmedia.com/5Rqat803GzqGzlFP8SC0gsp7R-GBzsjxQ6Ii5DNL5_c.jpg",
          "edited": false,
          "author_flair_css_class": null,
          "author_flair_richtext": [],
          "gildings": {},
          "post_hint": "link",
          "content_categories": null,
          "is_self": false,
          "mod_note": null,
          "created": 1420264621,
          "link_flair_type": "text",
          "wls": 6,
          "removed_by_category": null,
          "banned_by": null,
          "author_flair_type": "text",
          "domain": "medium.com",
          "allow_live_comments": false,
          "selftext_html": null,
          "likes": null,
          "suggested_sort": null,
          "banned_at_utc": null,
          "url_overridden_by_dest": "https://medium.com/@shazow/ssh-how-does-it-even-9e43586e4ffc",
          "view_count": null,
          "archived": true,
          "no_follow": false,
          "is_crosspostable": true,
          "pinned": false,
          "over_18": false,
          "preview": {
            "images": [
              {
                "source": {
                  "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?auto=webp&amp;s=e381f76b7c2f592a4afa908b5d28c484dcb65c16",
                  "width": 800,
                  "height": 313
                },
                "resolutions": [
                  {
                    "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=c237b3dceb33b2dea45ef471403fef42afe0f154",
                    "width": 108,
                    "height": 42
                  },
                  {
                    "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=bfb533673c38f95f0a62aae868ee4c327abf0664",
                    "width": 216,
                    "height": 84
                  },
                  {
                    "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=c3014e4ffa056cea7789cb529c749888c272bbd5",
                    "width": 320,
                    "height": 125
                  },
                  {
                    "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=0e5f86f49df0e74303731830b9cc994910f02466",
                    "width": 640,
                    "height": 250
                  }
                ],
                "variants": {},
                "id": "EhawVvuydO9L7eRjPLvVnzD5GyDMo6nD8MnxwiPMyR0"
              }
            ],
            "enabled": false
          },
          "all_awardings": [],
          "awarders": [],
          "media_only": false,
          "can_gild": true,
          "spoiler": false,
          "locked": false,
          "author_flair_text": null,
          "treatment_tags": [],
          "visited": false,
          "removed_by": null,
          "num_reports": null,
          "distinguished": null,
          "subreddit_id": "t5_2qh1a",
          "mod_reason_by": null,
          "removal_reason": null,
          "link_flair_background_color": "",
          "id": "2r539r",
          "is_robot_indexable": true,
          "report_reasons": null,
          "author": "MisterSnuggles",
          "discussion_type": null,
          "num_comments": 352,
          "send_replies": true,
          "whitelist_status": "all_ads",
          "contest_mode": false,
          "mod_reports": [],
          "author_patreon_flair": false,
          "author_flair_text_color": null,
          "permalink": "/r/linux/comments/2r539r/why_arent_we_using_ssh_for_everything/",
          "parent_whitelist_status": "all_ads",
          "stickied": false,
          "url": "https://medium.com/@shazow/ssh-how-does-it-even-9e43586e4ffc",
          "subreddit_subscribers": 550886,
          "created_utc": 1420235821,
          "num_crossposts": 0,
          "media": null,
          "is_video": false
        }
      },
      {
        "kind": "t3",
        "data": {
          "approved_at_utc": null,
          "subreddit": "sysadmin",
          "selftext": "",
          "author_fullname": "t2_7ccf",
          "saved": false,
          "mod_reason_title": null,
          "gilded": 0,
          "clicked": false,
          "title": "Why aren’t we using SSH for everything? — Medium",
          "link_flair_richtext": [],
          "subreddit_name_prefixed": "r/sysadmin",
          "hidden": false,
          "pwls": 6,
          "link_flair_css_class": null,
          "downs": 0,
          "thumbnail_height": 54,
          "top_awarded_type": null,
          "hide_score": false,
          "name": "t3_2r8es6",
          "quarantine": false,
          "link_flair_text_color": "dark",
          "upvote_ratio": 0.82,
          "author_flair_background_color": null,
          "subreddit_type": "public",
          "ups": 51,
          "total_awards_received": 0,
          "media_embed": {},
          "thumbnail_width": 140,
          "author_flair_template_id": null,
          "is_original_content": false,
          "user_reports": [],
          "secure_media": null,
          "is_reddit_media_domain": false,
          "is_meta": false,
          "category": null,
          "secure_media_embed": {},
          "link_flair_text": null,
          "can_mod_post": false,
          "score": 51,
          "approved_by": null,
          "author_premium": true,
          "thumbnail": "https://b.thumbs.redditmedia.com/5Rqat803GzqGzlFP8SC0gsp7R-GBzsjxQ6Ii5DNL5_c.jpg",
          "edited": false,
          "author_flair_css_class": null,
          "author_flair_richtext": [],
          "gildings": {},
          "post_hint": "link",
          "content_categories": null,
          "is_self": false,
          "mod_note": null,
          "created": 1420346485,
          "link_flair_type": "text",
          "wls": 6,
          "removed_by_category": null,
          "banned_by": null,
          "author_flair_type": "text",
          "domain": "medium.com",
          "allow_live_comments": false,
          "selftext_html": null,
          "likes": null,
          "suggested_sort": null,
          "banned_at_utc": null,
          "url_overridden_by_dest": "https://medium.com/@shazow/ssh-how-does-it-even-9e43586e4ffc",
          "view_count": null,
          "archived": true,
          "no_follow": false,
          "is_crosspostable": true,
          "pinned": false,
          "over_18": false,
          "preview": {
            "images": [
              {
                "source": {
                  "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?auto=webp&amp;s=e381f76b7c2f592a4afa908b5d28c484dcb65c16",
                  "width": 800,
                  "height": 313
                },
                "resolutions": [
                  {
                    "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=c237b3dceb33b2dea45ef471403fef42afe0f154",
                    "width": 108,
                    "height": 42
                  },
                  {
                    "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=bfb533673c38f95f0a62aae868ee4c327abf0664",
                    "width": 216,
                    "height": 84
                  },
                  {
                    "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=c3014e4ffa056cea7789cb529c749888c272bbd5",
                    "width": 320,
                    "height": 125
                  },
                  {
                    "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=0e5f86f49df0e74303731830b9cc994910f02466",
                    "width": 640,
                    "height": 250
                  }
                ],
                "variants": {},
                "id": "EhawVvuydO9L7eRjPLvVnzD5GyDMo6nD8MnxwiPMyR0"
              }
            ],
            "enabled": false
          },
          "all_awardings": [],
          "awarders": [],
          "media_only": false,
          "can_gild": true,
          "spoiler": false,
          "locked": false,
          "author_flair_text": null,
          "treatment_tags": [],
          "visited": false,
          "removed_by": null,
          "num_reports": null,
          "distinguished": null,
          "subreddit_id": "t5_2qnp7",
          "mod_reason_by": null,
          "removal_reason": null,
          "link_flair_background_color": "",
          "id": "2r8es6",
          "is_robot_indexable": true,
          "report_reasons": null,
          "author": "speckz",
          "discussion_type": null,
          "num_comments": 47,
          "send_replies": true,
          "whitelist_status": "all_ads",
          "contest_mode": false,
          "mod_reports": [],
          "author_patreon_flair": false,
          "author_flair_text_color": null,
          "permalink": "/r/sysadmin/comments/2r8es6/why_arent_we_using_ssh_for_everything_medium/",
          "parent_whitelist_status": "all_ads",
          "stickied": false,
          "url": "https://medium.com/@shazow/ssh-how-does-it-even-9e43586e4ffc",
          "subreddit_subscribers": 488582,
          "created_utc": 1420317685,
          "num_crossposts": 0,
          "media": null,
          "is_video": false
        }
      },
      {
        "kind": "t3",
        "data": {
          "approved_at_utc": null,
          "subreddit": "csclub",
          "selftext": "",
          "author_fullname": "t2_431tb",
          "saved": false,
          "mod_reason_title": null,
          "gilded": 0,
          "clicked": false,
          "title": "Why aren’t we using SSH for everything?",
          "link_flair_richtext": [],
          "subreddit_name_prefixed": "r/csclub",
          "hidden": false,
          "pwls": null,
          "link_flair_css_class": null,
          "downs": 0,
          "thumbnail_height": 54,
          "top_awarded_type": null,
          "hide_score": false,
          "name": "t3_2r5o9n",
          "quarantine": false,
          "link_flair_text_color": "dark",
          "upvote_ratio": 0.84,
          "author_flair_background_color": "",
          "subreddit_type": "public",
          "ups": 4,
          "total_awards_received": 0,
          "media_embed": {},
          "thumbnail_width": 140,
          "author_flair_template_id": null,
          "is_original_content": false,
          "user_reports": [],
          "secure_media": null,
          "is_reddit_media_domain": false,
          "is_meta": false,
          "category": null,
          "secure_media_embed": {},
          "link_flair_text": null,
          "can_mod_post": false,
          "score": 4,
          "approved_by": null,
          "author_premium": false,
          "thumbnail": "https://b.thumbs.redditmedia.com/5Rqat803GzqGzlFP8SC0gsp7R-GBzsjxQ6Ii5DNL5_c.jpg",
          "edited": false,
          "author_flair_css_class": "customflair-ieee",
          "author_flair_richtext": [],
          "gildings": {},
          "post_hint": "link",
          "content_categories": null,
          "is_self": false,
          "mod_note": null,
          "created": 1420275614,
          "link_flair_type": "text",
          "wls": null,
          "removed_by_category": null,
          "banned_by": null,
          "author_flair_type": "text",
          "domain": "medium.com",
          "allow_live_comments": false,
          "selftext_html": null,
          "likes": null,
          "suggested_sort": null,
          "banned_at_utc": null,
          "url_overridden_by_dest": "https://medium.com/@shazow/ssh-how-does-it-even-9e43586e4ffc",
          "view_count": null,
          "archived": true,
          "no_follow": false,
          "is_crosspostable": true,
          "pinned": false,
          "over_18": false,
          "preview": {
            "images": [
              {
                "source": {
                  "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?auto=webp&amp;s=e381f76b7c2f592a4afa908b5d28c484dcb65c16",
                  "width": 800,
                  "height": 313
                },
                "resolutions": [
                  {
                    "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=c237b3dceb33b2dea45ef471403fef42afe0f154",
                    "width": 108,
                    "height": 42
                  },
                  {
                    "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=bfb533673c38f95f0a62aae868ee4c327abf0664",
                    "width": 216,
                    "height": 84
                  },
                  {
                    "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=c3014e4ffa056cea7789cb529c749888c272bbd5",
                    "width": 320,
                    "height": 125
                  },
                  {
                    "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=0e5f86f49df0e74303731830b9cc994910f02466",
                    "width": 640,
                    "height": 250
                  }
                ],
                "variants": {},
                "id": "EhawVvuydO9L7eRjPLvVnzD5GyDMo6nD8MnxwiPMyR0"
              }
            ],
            "enabled": false
          },
          "all_awardings": [],
          "awarders": [],
          "media_only": false,
          "can_gild": true,
          "spoiler": false,
          "locked": false,
          "author_flair_text": "CEG Alum",
          "treatment_tags": [],
          "visited": false,
          "removed_by": null,
          "num_reports": null,
          "distinguished": null,
          "subreddit_id": "t5_2ry8l",
          "mod_reason_by": null,
          "removal_reason": null,
          "link_flair_background_color": "",
          "id": "2r5o9n",
          "is_robot_indexable": true,
          "report_reasons": null,
          "author": "uiri",
          "discussion_type": null,
          "num_comments": 0,
          "send_replies": false,
          "whitelist_status": null,
          "contest_mode": false,
          "mod_reports": [],
          "author_patreon_flair": false,
          "author_flair_text_color": "dark",
          "permalink": "/r/csclub/comments/2r5o9n/why_arent_we_using_ssh_for_everything/",
          "parent_whitelist_status": null,
          "stickied": false,
          "url": "https://medium.com/@shazow/ssh-how-does-it-even-9e43586e4ffc",
          "subreddit_subscribers": 27,
          "created_utc": 1420246814,
          "num_crossposts": 0,
          "media": null,
          "is_video": false
        }
      },
      {
        "kind": "t3",
        "data": {
          "approved_at_utc": null,
          "subreddit": "hackernews",
          "selftext": "",
          "author_fullname": "t2_ex7ry",
          "saved": false,
          "mod_reason_title": null,
          "gilded": 0,
          "clicked": false,
          "title": "Why aren’t we using SSH for everything?",
          "link_flair_richtext": [],
          "subreddit_name_prefixed": "r/hackernews",
          "hidden": false,
          "pwls": 6,
          "link_flair_css_class": null,
          "downs": 0,
          "thumbnail_height": 54,
          "top_awarded_type": null,
          "hide_score": false,
          "name": "t3_2r5364",
          "quarantine": false,
          "link_flair_text_color": "dark",
          "upvote_ratio": 0.86,
          "author_flair_background_color": null,
          "subreddit_type": "restricted",
          "ups": 5,
          "total_awards_received": 0,
          "media_embed": {},
          "thumbnail_width": 140,
          "author_flair_template_id": null,
          "is_original_content": false,
          "user_reports": [],
          "secure_media": null,
          "is_reddit_media_domain": false,
          "is_meta": false,
          "category": null,
          "secure_media_embed": {},
          "link_flair_text": null,
          "can_mod_post": false,
          "score": 5,
          "approved_by": null,
          "author_premium": false,
          "thumbnail": "https://b.thumbs.redditmedia.com/5Rqat803GzqGzlFP8SC0gsp7R-GBzsjxQ6Ii5DNL5_c.jpg",
          "edited": false,
          "author_flair_css_class": null,
          "author_flair_richtext": [],
          "gildings": {},
          "post_hint": "link",
          "content_categories": null,
          "is_self": false,
          "mod_note": null,
          "created": 1420264565,
          "link_flair_type": "text",
          "wls": 6,
          "removed_by_category": null,
          "banned_by": null,
          "author_flair_type": "text",
          "domain": "medium.com",
          "allow_live_comments": false,
          "selftext_html": null,
          "likes": null,
          "suggested_sort": null,
          "banned_at_utc": null,
          "url_overridden_by_dest": "https://medium.com/@shazow/ssh-how-does-it-even-9e43586e4ffc",
          "view_count": null,
          "archived": true,
          "no_follow": false,
          "is_crosspostable": true,
          "pinned": false,
          "over_18": false,
          "preview": {
            "images": [
              {
                "source": {
                  "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?auto=webp&amp;s=e381f76b7c2f592a4afa908b5d28c484dcb65c16",
                  "width": 800,
                  "height": 313
                },
                "resolutions": [
                  {
                    "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=c237b3dceb33b2dea45ef471403fef42afe0f154",
                    "width": 108,
                    "height": 42
                  },
                  {
                    "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=bfb533673c38f95f0a62aae868ee4c327abf0664",
                    "width": 216,
                    "height": 84
                  },
                  {
                    "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=c3014e4ffa056cea7789cb529c749888c272bbd5",
                    "width": 320,
                    "height": 125
                  },
                  {
                    "url": "https://external-preview.redd.it/ESfeNEDQSlJNZCQOs3VRr5nJRPO-N2uuBrZHS7rJsDI.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=0e5f86f49df0e74303731830b9cc994910f02466",
                    "width": 640,
                    "height": 250
                  }
                ],
                "variants": {},
                "id": "EhawVvuydO9L7eRjPLvVnzD5GyDMo6nD8MnxwiPMyR0"
              }
            ],
            "enabled": false
          },
          "all_awardings": [],
          "awarders": [],
          "media_only": false,
          "can_gild": true,
          "spoiler": false,
          "locked": false,
          "author_flair_text": null,
          "treatment_tags": [],
          "visited": false,
          "removed_by": null,
          "num_reports": null,
          "distinguished": null,
          "subreddit_id": "t5_2qhij",
          "mod_reason_by": null,
          "removal_reason": null,
          "link_flair_background_color": "",
          "id": "2r5364",
          "is_robot_indexable": true,
          "report_reasons": null,
          "author": "qznc_bot",
          "discussion_type": null,
          "num_comments": 1,
          "send_replies": false,
          "whitelist_status": "all_ads",
          "contest_mode": false,
          "mod_reports": [],
          "author_patreon_flair": false,
          "author_flair_text_color": null,
          "permalink": "/r/hackernews/comments/2r5364/why_arent_we_using_ssh_for_everything/",
          "parent_whitelist_status": "all_ads",
          "stickied": false,
          "url": "https://medium.com/@shazow/ssh-how-does-it-even-9e43586e4ffc",
          "subreddit_subscribers": 46294,
          "created_utc": 1420235765,
          "num_crossposts": 0,
          "media": null,
          "is_video": false
        }
      }
    ],
    "before": null
  }
}
`
